### ISSUE TITLE
Full error is not showing 

### ISSUE THREAD

**Issue by RameshDev92** [SoftwareMansion/stack-beautifier#2]
This is my stack trace 

Fatal Exception: com.facebook.react.common.JavascriptException: ReferenceError: ReferenceError: Can't find variable: Text

This error is located at:
    in n
    in v
    in RCTView
    in RCTView
    in RCTView
    in u
    in RCTView
    in u
    in C
    in n
    in P
    in RCTView
    in n
    in RCTView
    in u
    in PanGestureHandler
    in y
    in L
    in RCTView
    in _
    in C
    in b
    in v
    in v
    in c
    in b
    in k
    in RCTView
    in RCTView
    in c

This error is located at:
    in k
    in RCTView
    in RCTView
    in c, stack:
value@504:817
jr@90:48721
na@90:72881
ra@90:73371
Oa@90:80972
Wa@90:80310
Aa@90:79323
sa@90:78013
enqueueSetState@90:29425
setState@61:2231
dispatch@370:1264
<unknown>@377:1164
goToNextScreen@505:568
**<unknown>@505:942**
y@118:657
callTimers@118:2816
value@28:3311
<unknown>@28:822
value@28:2565
value@28:794

       at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
       at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:836)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
       at android.os.Looper.loop(Looper.java:203)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
       at java.lang.Thread.run(Thread.java:761).

But after using this command am not getting the file name where the crash occurred.

**C:\Users\mramesh>stack-beautifier C:\Users\mramesh\Desktop\reactNavigationPracti
ce\sourcemap.android.js -t C:\Users\mramesh\Desktop\crashreport.txt

Fatal Exception: com.facebook.react.common.JavascriptException: ReferenceError:
ReferenceError: Can't find variable: Text**

**Comment by claudioviola** [comment]
Me too. I have similar issue.
It doesn't return complete informations
