### ISSUE TITLE
V8 stack trace parse error

### ISSUE THREAD

**Issue by dnicolson** [SoftwareMansion/stack-beautifier#3]
The following error appears:
```
Error: Stack trace parse error at line 4: at Array.forEach (<anonymous>)
```
For the following stack trace:

```
TypeError: Cannot read property 'dispatchEvent' of null
    at n.dispatchEvent (https://local/lib.js:1:121618)
    at https://local/lib.js:1:51143
    at Array.forEach (<anonymous>)
    at p (https://local/lib.js:1:51031)
    at https://local/lib.js:1:50860
    at https://local/lib.js:1:122471
    at Arguments.<anonymous> (https://local/lib.js:1:123563)
    at Sk.push (https://securepubads.g.doubleclick.net/gpt/pubads_impl_2019082701.js:15:21134)
    at Ji.<anonymous> (https://securepubads.g.doubleclick.net/gpt/pubads_impl_2019082701.js:15:16445)
    at Ji.push (https://securepubads.g.doubleclick.net/gpt/pubads_impl_2019082701.js:15:15902)
```

This is the user agent:
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
```

**Comment by esutton** [comment]
Sadly same issue with a react native bundle.  

Does anyone have tips on how to make sense of the Crashlytics stack trace text?


```
stack-beautifier --version
1.0.2

stack-beautifier sourcemap.android.js -t mytrace.txt
/usr/local/lib/node_modules/stack-beautifier/stack-beautifier.js:123
        throw new Error(`Stack trace parse error at line ${i + 1}: ${line}`);
        ^

Error: Stack trace parse error at line 2: at .removeFile(index.android.bundle:474:6500)
    at processStack (/usr/local/lib/node_modules/stack-beautifier/stack-beautifier.js:123:15)
    at Interface.rl.on (/usr/local/lib/node_modules/stack-beautifier/stack-beautifier.js:76:19)
    at Interface.emit (events.js:203:15)
    at Interface.close (readline.js:397:8)
    at ReadStream.onend (readline.js:173:10)
    at ReadStream.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

File: mytrace.txt
```
Non-fatal Exception: io.invertase.firebase.crashlytics.UnhandledPromiseRejection: undefined is not an object (evaluating 't.includes')
       at .removeFile(index.android.bundle:474:6500)
       at .<unknown>(index.android.bundle:758:3472)
       at .y(index.android.bundle:105:596)
       at .<unknown>(index.android.bundle:105:2546)
       at .y(index.android.bundle:105:596)
       at .o(index.android.bundle:105:1483)
       at .<unknown>(index.android.bundle:105:1626)
       at .f(index.android.bundle:101:155)
       at .<unknown>(index.android.bundle:101:1012)
       at .y(index.android.bundle:107:657)
       at .C(index.android.bundle:107:1021)
       at .callImmediates(index.android.bundle:107:3216)
       at .callImmediates([native code]:0:0)
       at .value(index.android.bundle:25:3080)
       at .<unknown>(index.android.bundle:25:1264)
       at .value(index.android.bundle:25:2772)
       at .value(index.android.bundle:25:1234)
       at .value([native code]:0:0)
       at .value([native code]:0:0)
```

File: buildgradle
```
// https://stackoverflow.com/questions/34715106/how-to-add-sourcemap-in-react-native-for-production/34733906
project.ext.react = [
    entryFile: "index.js",
    enableHermes: false,  // clean and rebuild if changing    
    extraPackagerArgs: ["--sourcemap-output", 
    file("$buildDir/../../../sourcemap.android.js")]
]
```

**Comment by esutton** [comment]
Paring down my stack trace text to the first 3 or 4 lines, and adding a space after the stack trace function and before the opening parentheses fixed my  stack-beautifier **Stack trace parse error**.

File: mytrace.txt
```
# stack trace text copied from crashlytics after deleting all but first two lines
Non-fatal Exception: io.invertase.firebase.crashlytics.UnhandledPromiseRejection: undefined is not an object (evaluating 't.includes')
       at .removeFile(index.android.bundle:474:6500)
```


```
# Inserted a space after the 'removeFile' function and before opening '('  
# fixed the stack-beautifier "Stack trace parse error"

Non-fatal Exception: io.invertase.firebase.crashlytics.UnhandledPromiseRejection: undefined is not an object (evaluating 't.includes')
       at .removeFile (index.android.bundle:474:6500)
```

Success!  

Found the origination of my removeFile function error in source file **Utility.js:567:17**  
```
stack-beautifier sourcemap.android.js -t mytrace.txt
Non-fatal Exception: io.invertase.firebase.crashlytics.UnhandledPromiseRejection: undefined is not an object (evaluating 't.includes')
  at includes (/Users/eddie/Documents/projects/react-native/myapp/v1.6.1146/source/app/components/Utility.js:567:17)
```

Also, stack-beautifier seems to crash when it encounters '**[native code]**' in the trace. I deleted all trace lines starting at first **[native code]** line.
```
      # Delete all stack trace lines startign at first found line containing [native code]
       at .callImmediates ([native code]:0:0)
```

**Comment by esutton** [comment]
This seems to work for me if I remove all stack trace lines starting with first line containing "**[native code]**"
```
npx metro-symbolicate sourcemap.android.js < bug-android-stack-trace.txt
npx metro-symbolicate sourcemap.ios.js < bug-ios-stack-trace.txt
```
See: https://reactnative.dev/docs/next/symbolication
